//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Tools.Database.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Tools.Database.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specifed column does not belong to the specified table.
        /// </summary>
        internal static string InvalidOperationColumnDoesNotBelongToTable {
            get {
                return ResourceManager.GetString("InvalidOperationColumnDoesNotBelongToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data row does not belong to the table type that owns this object..
        /// </summary>
        internal static string InvalidOperationDataRowTableMismatch {
            get {
                return ResourceManager.GetString("InvalidOperationDataRowTableMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified data table has not been registered.
        /// </summary>
        internal static string InvalidOperationDataTableNotRegistered {
            get {
                return ResourceManager.GetString("InvalidOperationDataTableNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table returned an empty string for ddl creation.
        /// </summary>
        internal static string InvalidOperationEmptyDdl {
            get {
                return ResourceManager.GetString("InvalidOperationEmptyDdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table is read only.
        /// </summary>
        internal static string InvalidOperationTableIsReadOnly {
            get {
                return ResourceManager.GetString("InvalidOperationTableIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not implemented.
        /// </summary>
        internal static string MethodNotImplemented {
            get {
                return ResourceManager.GetString("MethodNotImplemented", resourceCulture);
            }
        }
    }
}
