//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restless.Tools.Utility.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restless.Tools.Utility.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object ({0}) is not allowed to be null..
        /// </summary>
        internal static string ArgumentNullValidateNull {
            get {
                return ResourceManager.GetString("ArgumentNullValidateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string ({0}) is not allowed to be null or empty..
        /// </summary>
        internal static string ArgumentNullValidateNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullValidateNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for {0} is out of range. Must be between {1} - {2}.
        /// </summary>
        internal static string ArgumentOutOfRangeValidateInteger {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeValidateInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array {0} must have a minimum length of {1}.
        /// </summary>
        internal static string ArgumentValidateArray {
            get {
                return ResourceManager.GetString("ArgumentValidateArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the specified file. Please make sure the path and file name is correct..
        /// </summary>
        internal static string InvalidOperationCannotOpenFile {
            get {
                return ResourceManager.GetString("InvalidOperationCannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row does not belong to the {0} table.
        /// </summary>
        internal static string InvalidOperationDataRowMustBeTable {
            get {
                return ResourceManager.GetString("InvalidOperationDataRowMustBeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string UnhandledExceptionCaption {
            get {
                return ResourceManager.GetString("UnhandledExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured in the current domain.
        /// </summary>
        internal static string UnhandledExceptionCurrentDomain {
            get {
                return ResourceManager.GetString("UnhandledExceptionCurrentDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now attempt to shutdown gracefully..
        /// </summary>
        internal static string UnhandledExceptionMessageFooter {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred..
        /// </summary>
        internal static string UnhandledExceptionMessageHeader {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unspecified).
        /// </summary>
        internal static string UnspecifiedName {
            get {
                return ResourceManager.GetString("UnspecifiedName", resourceCulture);
            }
        }
    }
}
